title: Dylan James-Kavanaugh
logo: images/headshot.jpg
description: Dylans Portfolio showcasing education, work experience, projects, and additional information.
# show_downloads: false
theme: jekyll-theme-minimal
