title: Dylan James-Kavanaugh
logo: images/headshot.jpg
description: Dylan's Portfolio showcasing eduction, projects, work experience, and additional information about DJK.
show_downloads: false
theme: jekyll-theme-midnight
